DROP TABLE IF EXISTS rag_query_logs CASCADE;
DROP TABLE IF EXISTS kb_assets CASCADE;
DROP TABLE IF EXISTS kb_chunks CASCADE;
DROP TABLE IF EXISTS data_assets CASCADE;
DROP TABLE IF EXISTS kb_documents CASCADE;
DROP EXTENSION IF EXISTS vector CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;