from __future__ import annotations

from .bus import CommandSpec
from .asset_production import (
    entity_adopt_image,
    entity_extract,
    entity_generate_asset_prompt,
    entity_generate_images,
    entity_generate_setting,
    entity_profile_list,
    entity_profile_search,
    entity_profile_show,
    entity_profile_update,
    visual_style_delete,
    visual_style_list,
    visual_style_save,
)
from .handlers import (
    agent_result_read, asset_delete, asset_import, asset_list, asset_rename, config_llm_test, config_show,
    config_video_test, document_import, entity_create, entity_delete,
    entity_list,
    entity_show, entity_update,
    preprocess_split, project_create, project_delete,
    file_list, file_read, file_write, project_list, project_settings_update, project_show, project_update,
    prompt_template_delete, prompt_template_list,
    prompt_template_save, prompt_template_show, prompt_template_versions, prompt_card_delete,
    prompt_card_generate, prompt_card_list, prompt_card_lock, prompt_card_rerun, prompt_card_show, prompt_card_update, script_convert,
    script_save, script_show, segment_delete, segment_list, segment_reorder, segment_show,
    segment_update, video_request, video_task_delete, video_task_list, video_task_show,
    workflow_status, workspace_show,
)


def build_command_registry() -> dict[str, CommandSpec]:
    projects = ("projects",)
    workspace = ("workspace", "projects")
    assets = ("assets", "entities", "asset-production", "projects")
    entities = ("entities", "asset-production", "projects")
    asset_production = ("asset-production", "projects")
    templates = ("templates",)
    prompt_cards = ("prompt-cards", "projects")
    videos = ("videos", "projects")

    def spec(
        command_id,
        label,
        handler,
        schema,
        *,
        mutation=False,
        project=False,
        confirmation="none",
        description="",
        effects=(),
    ):
        return CommandSpec(
            command_id,
            label,
            handler,
            schema,
            mutation,
            project,
            confirmation,
            description,
            tuple(effects),
        )

    return {
        "agent-result.read": spec("agent-result.read", "读取工具结果", agent_result_read, {"project_id": "string", "result_ref": "string", "offset": "number?", "max_chars": "number?"}, project=True, description="按安全引用分段读取当前项目的持久化大型工具结果"),
        "project.list": spec("project.list", "列出项目", project_list, {}, description="列出未删除项目"),
        "project.show": spec("project.show", "查看项目", project_show, {"project_id": "string"}, project=True),
        "project.create": spec("project.create", "创建项目", project_create, {"name": "string", "category": "string", "description": "string"}, mutation=True, confirmation="write", effects=projects),
        "project.update": spec("project.update", "更新项目", project_update, {"project_id": "string", "name": "string?", "category": "string?", "description": "string?"}, mutation=True, project=True, confirmation="write", effects=projects),
        "project.settings.update": spec(
            "project.settings.update",
            "更新项目设置",
            project_settings_update,
            {
                "project_id": "string",
                "project_style_prompt": "string?",
                "expected_total_duration_seconds": "number?",
                "default_aspect_ratio": "string?",
                "default_video_duration": "number?",
                "default_video_model": "string?",
                "default_resolution": "string?",
                "output_root": "string?",
                "source_assets_root": "string?",
                "data_root": "string?",
                "revision": "number?",
            },
            mutation=True,
            project=True,
            confirmation="write",
            description="更新项目级设置；生成项目风格提示词后使用 project_style_prompt 写入",
            effects=workspace,
        ),
        "project.delete": spec("project.delete", "删除项目", project_delete, {"project_id": "string"}, mutation=True, project=True, confirmation="destructive", effects=projects),
        "workspace.show": spec("workspace.show", "查看项目工作区", workspace_show, {"project_id": "string"}, project=True),
        "document.import": spec("document.import", "导入文档", document_import, {"project_id": "string", "path": "string"}, mutation=True, project=True, confirmation="write", effects=workspace),
        "preprocess.split": spec("preprocess.split", "切分原文", preprocess_split, {"project_id": "string", "strategy": "chapter|custom_regex|manual|length|duration", "custom_pattern": "string?", "duration_minutes": "number?", "content": "string?"}, mutation=True, project=True, confirmation="overwrite", effects=workspace),
        "segment.list": spec("segment.list", "列出分集", segment_list, {"project_id": "string"}, project=True),
        "segment.show": spec("segment.show", "查看分集", segment_show, {"project_id": "string", "segment_id": "string"}, project=True),
        "segment.update": spec("segment.update", "修改分集", segment_update, {"project_id": "string", "segment_id": "string", "title": "string?", "content": "string?", "revision": "number?"}, mutation=True, project=True, confirmation="write", effects=workspace),
        "segment.reorder": spec("segment.reorder", "调整分集顺序", segment_reorder, {"project_id": "string", "ids": "string[]", "revision": "number?"}, mutation=True, project=True, confirmation="write", effects=workspace),
        "segment.delete": spec("segment.delete", "删除分集", segment_delete, {"project_id": "string", "segment_id": "string", "revision": "number?"}, mutation=True, project=True, confirmation="destructive", effects=workspace),
        "script.show": spec("script.show", "查看剧本", script_show, {"project_id": "string", "segment_id": "string?"}, project=True, description="读取已入库剧本正文；可读取全项目或指定分集"),
        "script.save": spec("script.save", "保存剧本", script_save, {"project_id": "string", "segment_id": "string", "content": "string", "revision": "number?"}, mutation=True, project=True, confirmation="write", effects=workspace),
        "script.convert": spec("script.convert", "转换剧本", script_convert, {"project_id": "string", "segment_id": "string", "source_format": "script|source", "content": "string?", "content_type": "string?", "template_id": "string?", "revision": "number?"}, mutation=True, project=True, confirmation="llm", effects=workspace),
        "file.list": spec("file.list", "列出项目文件", file_list, {"project_id": "string", "path": "string?", "limit": "number?"}, project=True, description="列出当前项目数据目录中的文件，path 必须是项目内相对目录"),
        "file.read": spec("file.read", "读取项目文本文件", file_read, {"project_id": "string", "path": "string", "max_chars": "number?"}, project=True, description="读取当前项目数据目录中的 UTF-8 文本文件，禁止访问项目外路径"),
        "file.write": spec("file.write", "写入项目文本文件", file_write, {"project_id": "string", "path": "string", "content": "string"}, mutation=True, project=True, confirmation="write", description="在当前项目数据目录写入 UTF-8 文本文件；覆盖前需要确认", effects=workspace),
        "asset.list": spec("asset.list", "列出素材", asset_list, {"project_id": "string"}, project=True),
        "asset.import": spec("asset.import", "导入素材", asset_import, {"project_id": "string", "paths": "string[]"}, mutation=True, project=True, confirmation="write", effects=assets),
        "asset.rename": spec("asset.rename", "重命名素材", asset_rename, {"project_id": "string", "asset_path": "string", "filename": "string"}, mutation=True, project=True, confirmation="write", effects=assets),
        "asset.delete": spec("asset.delete", "删除素材", asset_delete, {"project_id": "string", "asset_path": "string"}, mutation=True, project=True, confirmation="destructive", effects=assets),
        "entity.list": spec("entity.list", "列出实体卡", entity_list, {"project_id": "string"}, project=True),
        "entity.show": spec("entity.show", "查看实体卡", entity_show, {"project_id": "string", "entity_id": "string"}, project=True),
        "entity-profile.list": spec("entity-profile.list", "列出实体档案", entity_profile_list, {"project_id": "string"}, project=True, description="读取资源管理实体清单中的现有 V3 实体档案；生成资产前应优先调用或使用项目上下文中的档案"),
        "entity-profile.search": spec("entity-profile.search", "搜索实体档案", entity_profile_search, {"project_id": "string", "query": "string", "type": "character|scene|prop?", "limit": "number?"}, project=True, description="按名称和别名搜索实体档案并返回少量候选；索引未命中或已截断时使用"),
        "entity-profile.show": spec("entity-profile.show", "查看实体档案", entity_profile_show, {"project_id": "string", "profile_id": "string"}, project=True, description="读取指定实体档案、已有设定、资产提示词、视觉风格、预设和图片任务"),
        "entity-profile.update": spec("entity-profile.update", "更新实体档案", entity_profile_update, {"project_id": "string", "profile_id": "string", "canonical_name": "string?", "type": "character|scene|prop?", "aliases": "string[]?", "role": "string?", "importance": "S|A|B|C?", "setting": "string?", "status": "string?"}, mutation=True, project=True, confirmation="write", description="人工更新已有实体档案，不重新提取剧本", effects=asset_production),
        "visual-style.list": spec("visual-style.list", "列出资产视觉风格", visual_style_list, {"project_id": "string"}, project=True, description="列出资产生成页面的视觉风格预设及版本；修改前可先读取"),
        "visual-style.save": spec("visual-style.save", "保存资产视觉风格", visual_style_save, {"project_id": "string", "style_id": "string?", "name": "string", "prompt": "string", "negative_prompt": "string?", "reference_asset_ids": "string[]?", "is_active": "boolean?"}, mutation=True, project=True, confirmation="write", description="新建或基于 style_id 生成新版资产视觉风格；这是资源管理 > 资产生成 > 风格预设的唯一写入工具，不要误用 project.settings.update", effects=asset_production),
        "visual-style.delete": spec("visual-style.delete", "删除资产视觉风格", visual_style_delete, {"project_id": "string", "style_id": "string"}, mutation=True, project=True, confirmation="destructive", description="删除未被资产提示词引用的视觉风格版本", effects=asset_production),
        "entity.create": spec("entity.create", "创建实体卡", entity_create, {"project_id": "string", "name": "string", "type": "character|scene|prop", "state": "string?"}, mutation=True, project=True, confirmation="write", effects=entities),
        "entity.update": spec("entity.update", "更新实体卡", entity_update, {"project_id": "string", "entity_id": "string", "name": "string?", "type": "string?", "state": "string?"}, mutation=True, project=True, confirmation="write", effects=entities),
        "entity.delete": spec("entity.delete", "删除实体卡", entity_delete, {"project_id": "string", "entity_id": "string"}, mutation=True, project=True, confirmation="destructive", effects=entities),
        "entity.extract": spec("entity.extract", "提取实体", entity_extract, {"project_id": "string", "segment_ids": "string[]?"}, mutation=True, project=True, confirmation="llm", effects=asset_production),
        "entity.generate-setting": spec("entity.generate-setting", "生成实体设定", entity_generate_setting, {"project_id": "string", "profile_id": "string"}, mutation=True, project=True, confirmation="llm", effects=asset_production),
        "entity.generate-asset-prompt": spec("entity.generate-asset-prompt", "生成实体资产提示词", entity_generate_asset_prompt, {"project_id": "string", "profile_id": "string", "variant_id": "string?", "view_type": "string?"}, mutation=True, project=True, confirmation="llm", effects=asset_production),
        "entity.generate-images": spec("entity.generate-images", "生成实体图片", entity_generate_images, {"project_id": "string", "asset_prompt_id": "string"}, mutation=True, project=True, confirmation="external", effects=asset_production),
        "entity.adopt-image": spec("entity.adopt-image", "采用实体图片", entity_adopt_image, {"project_id": "string", "output_id": "string"}, mutation=True, project=True, confirmation="write", effects=assets),
        "prompt-template.list": spec("prompt-template.list", "列出提示词模板", prompt_template_list, {}),
        "prompt-template.show": spec("prompt-template.show", "查看提示词模板", prompt_template_show, {"template_id": "string"}),
        "prompt-template.save": spec("prompt-template.save", "保存提示词模板", prompt_template_save, {"template_id": "string?", "name": "string", "category": "string", "template": "string"}, mutation=True, confirmation="write", effects=templates),
        "prompt-template.delete": spec("prompt-template.delete", "删除提示词模板", prompt_template_delete, {"template_id": "string"}, mutation=True, confirmation="destructive", effects=templates),
        "prompt-template.versions": spec("prompt-template.versions", "查看提示词模板版本", prompt_template_versions, {"template_id": "string"}),
        "prompt-card.list": spec("prompt-card.list", "列出提示词卡", prompt_card_list, {"project_id": "string", "segment_id": "string?"}, project=True),
        "prompt-card.show": spec("prompt-card.show", "查看提示词卡", prompt_card_show, {"card_id": "string"}),
        "prompt-card.update": spec("prompt-card.update", "修改提示词卡", prompt_card_update, {"card_id": "string", "title": "string?", "prompt_text": "string?", "anchor_text": "string?", "duration": "number?", "status": "string?"}, mutation=True, confirmation="write", effects=prompt_cards),
        "prompt-card.lock": spec("prompt-card.lock", "锁定或解锁提示词卡", prompt_card_lock, {"card_id": "string", "locked": "boolean"}, mutation=True, confirmation="write", effects=prompt_cards),
        "prompt-card.delete": spec("prompt-card.delete", "删除提示词卡", prompt_card_delete, {"card_id": "string"}, mutation=True, confirmation="destructive", effects=prompt_cards),
        "prompt-card.generate": spec("prompt-card.generate", "生成提示词卡", prompt_card_generate, {"project_id": "string", "segment_id": "string", "script": "string?", "template_id": "string?", "max_duration_seconds": "number?", "expected_total_duration_seconds": "number?", "replace": "boolean"}, mutation=True, project=True, confirmation="llm", effects=prompt_cards),
        "prompt-card.rerun": spec("prompt-card.rerun", "重跑提示词卡", prompt_card_rerun, {"card_id": "string", "script": "string?", "template_id": "string?", "max_duration_seconds": "number?"}, mutation=True, confirmation="llm", effects=prompt_cards),
        "config.show": spec("config.show", "查看服务配置", config_show, {}),
        "config.llm-test": spec("config.llm-test", "测试 LLM 连通性", config_llm_test, {"use_case": "string"}),
        "config.video-test": spec("config.video-test", "测试视频服务连通性", config_video_test, {}),
        "video-task.list": spec("video-task.list", "列出视频任务", video_task_list, {"project_id": "string", "segment_id": "string?"}, project=True),
        "video-task.show": spec("video-task.show", "查看视频任务", video_task_show, {"task_id": "string"}),
        "video-task.delete": spec("video-task.delete", "删除视频任务", video_task_delete, {"task_id": "string"}, mutation=True, confirmation="destructive", effects=videos),
        "video.request": spec("video.request", "提交视频生成请求", video_request, {"project_id": "string", "segment_id": "string", "card_id": "string?", "prompt": "string?", "model": "string?", "aspect_ratio": "string?", "resolution": "string?", "duration": "number?", "preview": "boolean"}, mutation=True, project=True, confirmation="external", effects=videos),
        "workflow.status": spec("workflow.status", "查看工作流状态", workflow_status, {"project_id": "string"}, project=True),
    }
